//
// Generated file, do not edit! Created by opp_msgc 4.2 from applications/BitTorrentSPD/BTSPDThreatHandlerMsgs.msg.
//

#ifndef _BTSPDTHREATHANDLERMSGS_M_H_
#define _BTSPDTHREATHANDLERMSGS_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>applications/BitTorrentSPD/BTSPDThreatHandlerMsgs.msg</tt> by opp_msgc.
 * <pre>
 * enum ATTACK_TYPE
 * {
 *     ADDR_FOUND_ACTIVE_CONN = 1; 
 *     ADDR_FOUND_PASSIVE_CONN = 2; 
 * }
 * </pre>
 */
enum ATTACK_TYPE {
    ADDR_FOUND_ACTIVE_CONN = 1,
    ADDR_FOUND_PASSIVE_CONN = 2
};

/**
 * Class generated from <tt>applications/BitTorrentSPD/BTSPDThreatHandlerMsgs.msg</tt> by opp_msgc.
 * <pre>
 * message BTSPD_NewAddrFound
 * {
 *     @omitGetVerb(true);
 *     string addr;
 *     string port;
 * }
 * </pre>
 */
class BTSPD_NewAddrFound : public ::cMessage
{
  protected:
    opp_string addr_var;
    opp_string port_var;

  private:
    void copy(const BTSPD_NewAddrFound& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BTSPD_NewAddrFound&);

  public:
    BTSPD_NewAddrFound(const char *name=NULL, int kind=0);
    BTSPD_NewAddrFound(const BTSPD_NewAddrFound& other);
    virtual ~BTSPD_NewAddrFound();
    BTSPD_NewAddrFound& operator=(const BTSPD_NewAddrFound& other);
    virtual BTSPD_NewAddrFound *dup() const {return new BTSPD_NewAddrFound(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * addr() const;
    virtual void setAddr(const char * addr);
    virtual const char * port() const;
    virtual void setPort(const char * port);
};

inline void doPacking(cCommBuffer *b, BTSPD_NewAddrFound& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BTSPD_NewAddrFound& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>applications/BitTorrentSPD/BTSPDThreatHandlerMsgs.msg</tt> by opp_msgc.
 * <pre>
 * packet BTSPDAttackMessage
 * {
 *     @omitGetVerb(true);
 *     string attacker;
 *     string victim;
 *     
 *     unsigned int attackType @enum(ATTACK_TYPE);
 *     
 * }
 * </pre>
 */
class BTSPDAttackMessage : public ::cPacket
{
  protected:
    opp_string attacker_var;
    opp_string victim_var;
    unsigned int attackType_var;

  private:
    void copy(const BTSPDAttackMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BTSPDAttackMessage&);

  public:
    BTSPDAttackMessage(const char *name=NULL, int kind=0);
    BTSPDAttackMessage(const BTSPDAttackMessage& other);
    virtual ~BTSPDAttackMessage();
    BTSPDAttackMessage& operator=(const BTSPDAttackMessage& other);
    virtual BTSPDAttackMessage *dup() const {return new BTSPDAttackMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * attacker() const;
    virtual void setAttacker(const char * attacker);
    virtual const char * victim() const;
    virtual void setVictim(const char * victim);
    virtual unsigned int attackType() const;
    virtual void setAttackType(unsigned int attackType);
};

inline void doPacking(cCommBuffer *b, BTSPDAttackMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BTSPDAttackMessage& obj) {obj.parsimUnpack(b);}


#endif // _BTSPDTHREATHANDLERMSGS_M_H_
