#ifndef __INET_BTSPDCOMMONMSGTYPES_H_
#define __INET_BTSPDCOMMONMSGTYPES_H_

#define BTSPD_ATTACK_MSG_TYPE                   1001
#define BTSPD_NEW_TCP_ADDR                      1002
#define BTSPD_GET_PATCH_PLATFORM_INFO_MSG_TYPE  1003
#define BTPSPD_PATCH_INFO_RES_MSG_TYPE          1004

#define BTSPD_VULNERABILITY_FIXED_MSG_TYPE      1501
#define BTSPD_INFECTED_MSG_TYPE                 1502
#define BTSPD_INFECTION_CLEANED_MSG_TYPE        1503

#endif
