//
// Generated file, do not edit! Created by opp_msgc 4.2 from applications/BitTorrentSPD/BTSPDPatchInfoMsgs.msg.
//

#ifndef _BTSPDPATCHINFOMSGS_M_H_
#define _BTSPDPATCHINFOMSGS_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>applications/BitTorrentSPD/BTSPDPatchInfoMsgs.msg</tt> by opp_msgc.
 * <pre>
 * packet BTSPDPatchInfoMsg
 * {
 *     @omitGetVerb(true);
 *     string platform;    
 * }
 * </pre>
 */
class BTSPDPatchInfoMsg : public ::cPacket
{
  protected:
    opp_string platform_var;

  private:
    void copy(const BTSPDPatchInfoMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BTSPDPatchInfoMsg&);

  public:
    BTSPDPatchInfoMsg(const char *name=NULL, int kind=0);
    BTSPDPatchInfoMsg(const BTSPDPatchInfoMsg& other);
    virtual ~BTSPDPatchInfoMsg();
    BTSPDPatchInfoMsg& operator=(const BTSPDPatchInfoMsg& other);
    virtual BTSPDPatchInfoMsg *dup() const {return new BTSPDPatchInfoMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * platform() const;
    virtual void setPlatform(const char * platform);
};

inline void doPacking(cCommBuffer *b, BTSPDPatchInfoMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BTSPDPatchInfoMsg& obj) {obj.parsimUnpack(b);}


#endif // _BTSPDPATCHINFOMSGS_M_H_
