#ifndef __INET_BTSPDCOMMONMSGTYPES_H_
#define __INET_BTSPDCOMMONMSGTYPES_H_

#define BTSPD_ATTACK_MSG_TYPE                   1001
#define BTSPD_NEW_TCP_ADDR                      1002
#define BTSPD_GET_PATCH_PLATFORM_INFO_MSG_TYPE  1003
#define BTPSPD_PATCH_INFO_RES_MSG_TYPE          1004

#define BTSPD_VULNERABILITY_FIXED_MSG_TYPE      1501
#define BTSPD_INFECTED_MSG_TYPE                 1502
#define BTSPD_INFECTION_CLEANED_MSG_TYPE        1503


#define BTSPD_CONN_TRACK_IP_TO_NAME_MAP_MSG_TYPE        1601
#define BTSPD_CONN_TRACK_NEWCONN_MSG_TYPE               1602
#define BTSPD_CONN_TRACK_CONN_DROP_MSG_TYPE             1603
#define BTSPD_CONN_TRACK_NODE_CREATION_MSG_TYPE         1604
#define BTSPD_CONN_TRACK_CONN_DWL_COMPLETE_MSG_TYPE     1605

#endif
